### ISSUE TITLE
Update Hiera 3 to Hiera 5

### ISSUE THREAD

**Issue by tspeigner** [maju6406/pe_code_manager_easy_setup#1]
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Warning: The function 'hiera' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/4.9.4/reference/deprecated_language.html
   (file & line not available)
Warning: Unknown variable: '::code_manager_mv_old_code'. at /etc/puppetlabs/code/environments/production/modules/pe_code_manager_webhook/manifests/code_manager.pp:125:6

**Comment by maju6406** [comment]
This should be resolved now.
